#!/bin/bash

read -p "Enter The No1 : " number1
read -p "Enter The No2 : " number2
read -p "Enter The No3 : " number3

if [ $number1 -gt $number2 ] && [ $number1 -gt $number3 ]; then
    echo "${number1} Is Greatest"
elif [ $number2 -gt $number1 ] && [ $number2 -gt $number3 ]; then
    echo "${number2} Is Greatest"
else
    echo "${number3} Is Greatest"
fi
